# 資材ビルド
FROM node:18-bullseye as frontend-build

WORKDIR /build/frontend
COPY ./frontend .
WORKDIR /build/frontend/ow_system
ENV NODE_ENV=docker
RUN npm install && npm run build

# デプロイ
FROM nginx:latest

COPY --from=frontend-build /build/frontend/ow_system/build /usr/share/nginx/html
COPY ./webserver/default.conf /etc/nginx/conf.d/default.conf
